<?php
echo "Prueba de la variable GLOBALS:";
echo "<br>";
echo "<br>";
print_r($GLOBALS);
echo "<br>"; 
echo "<br>"; 
echo "<br>"; 
echo "Prueba de la variable _SERVER:";
echo "<br>";
echo "<br>";
print_r($_SERVER);
echo "<br>"; 
echo "<br>"; 
echo "<br>"; 
echo "Prueba de la variable _GET:";
echo "<br>";
echo "<br>";
print_r($_GET);
echo "<br>"; 
echo "<br>"; 
echo "<br>"; 
echo "Prueba de la variable _POST:";
echo "<br>";
echo "<br>";
print_r($_POST);
echo "<br>"; 
echo "<br>"; 
echo "<br>"; 
echo "Prueba de la variable _FILES:";
echo "<br>";
echo "<br>";
print_r($_FILES);
echo "<br>"; 
echo "<br>"; 
echo "<br>"; 
echo "Prueba de la variable _COOKIE:";
echo "<br>";
echo "<br>";
print_r($_COOKIE);
echo "<br>"; 
echo "<br>"; 
echo "<br>"; 
echo "Prueba de la variable _SESSION:";
echo "<br>";
echo "<br>";
print_r($_SESSION);
echo "<br>"; 
echo "<br>"; 
echo "<br>"; 
echo "Prueba de la variable _REQUEST:";
echo "<br>";
echo "<br>";
print_r($_REQUEST);
echo "<br>"; 
echo "<br>"; 
echo "<br>"; 
echo "Prueba de la variable _ENV:";
echo "<br>";
echo "<br>";
print_r($_ENV);
?>